/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.feature.dbhelper.Database;
import org.feature.dbhelper.DatabaseInitService;
import org.feature.dbhelper.DatabasePopulateService;
import org.feature.dbhelper.DatabaseQueryService;
import org.feature.query_into_object.*;

import java.util.List;

public class App {

    public static void main(String[] args) {
        Database database = Database.getInstance();
        new DatabaseInitService().initDb(database);
        new DatabasePopulateService().populateDb(database);

        DatabaseQueryService databaseQueryService = new DatabaseQueryService(database);

        List<MaxProjectCountClient> maxProjectCountClients = databaseQueryService.findMaxProjectsClient();
        for (MaxProjectCountClient maxProjectCountClient : maxProjectCountClients) {
            System.out.println(maxProjectCountClient);
        }

        System.out.println("\n");

        List<MaxSalaryWorker> maxSalaryWorkerList = databaseQueryService.findMaxSalaryWorker();
        for (MaxSalaryWorker maxSalaryWorker : maxSalaryWorkerList) {
            System.out.println(maxSalaryWorker);
        }

        System.out.println("\n");

        List<LongestProject> longestProjectList = databaseQueryService.findLongestProject();
        for (LongestProject longestProject : longestProjectList) {
            System.out.println(longestProject);
        }

        System.out.println("\n");

        List<YoungestEldestWorkers> youngestEldestWorkersList = databaseQueryService.findYoungestEldestWorkers();
        for (YoungestEldestWorkers youngestEldestWorkers : youngestEldestWorkersList) {
            System.out.println(youngestEldestWorkers);
        }

        System.out.println("\n");

        List<ProjectPrices> projectPricesList = databaseQueryService.printProjectPrices();
        for (ProjectPrices projectPrices : projectPricesList) {
            System.out.println(projectPrices);
        }
    }
}
